/*
  # Desativar RLS em Todas as Tabelas Existentes
*/

ALTER TABLE accounting_export_mappings DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_admins DISABLE ROW LEVEL SECURITY;
ALTER TABLE bank_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE bank_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE calendario_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE cash_batch_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE cash_batches DISABLE ROW LEVEL SECURITY;
ALTER TABLE cash_books DISABLE ROW LEVEL SECURITY;
ALTER TABLE cash_closings DISABLE ROW LEVEL SECURITY;
ALTER TABLE cash_ledger DISABLE ROW LEVEL SECURITY;
ALTER TABLE caucao_movimentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE config DISABLE ROW LEVEL SECURITY;
ALTER TABLE contratos_locacao DISABLE ROW LEVEL SECURITY;
ALTER TABLE custos_fixos DISABLE ROW LEVEL SECURITY;
ALTER TABLE diarista_lancamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE diarista_pagamentos_semanais DISABLE ROW LEVEL SECURITY;
ALTER TABLE diarista_ponto DISABLE ROW LEVEL SECURITY;
ALTER TABLE diaristas DISABLE ROW LEVEL SECURITY;
ALTER TABLE feriados DISABLE ROW LEVEL SECURITY;
ALTER TABLE folha_pagamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE funcionarios_mensalistas DISABLE ROW LEVEL SECURITY;
ALTER TABLE locacoes DISABLE ROW LEVEL SECURITY;
ALTER TABLE locacoes_contratos DISABLE ROW LEVEL SECURITY;
ALTER TABLE maquinas DISABLE ROW LEVEL SECURITY;
ALTER TABLE mensalista_faltas DISABLE ROW LEVEL SECURITY;
ALTER TABLE mensalista_pagamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE mensalista_pagamentos_competencia DISABLE ROW LEVEL SECURITY;
ALTER TABLE obras DISABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_runs DISABLE ROW LEVEL SECURITY;
ALTER TABLE receitas DISABLE ROW LEVEL SECURITY;
ALTER TABLE receitas_parcelas DISABLE ROW LEVEL SECURITY;
ALTER TABLE reconciliation_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE vt_ajustes DISABLE ROW LEVEL SECURITY;
