name: Extract project

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository (with credentials)
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Find .zip in repo root
        run: |
          ZIP_FILE="$(find . -maxdepth 1 -type f -iname '*.zip' -print -quit || true)"
          if [ -z "$ZIP_FILE" ]; then
            echo "Nenhum .zip encontrado na raiz do repositório."
            exit 1
          fi
          echo "Encontrado: $ZIP_FILE"
          unzip -q "$ZIP_FILE" -d extracted

      - name: Move extracted files to repo root
        run: |
          shopt -s dotglob || true
          cp -a extracted/* .
          rm -rf extracted
          echo "✅ Arquivos extraídos com sucesso!"

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "Yohan Linero"
          git config user.email "yuricv89@hotmail.com"
          git remote set-url origin "https://NomasIA:${GH_PAT}@github.com/NomasIA/Aguia-finance.git"
          git add -A
          git commit -m "Extraído automaticamente pelo GitHub Actions" || echo "Sem alterações para commitar"
          git push origin HEAD:${{ github.ref_name }}

          # após o commit, cria ou atualiza a branch secundária
          git checkout -B extracted-by-actions
          git push origin extracted-by-actions --force
          echo "🚀 Branch 'extracted-by-actions' atualizada com sucesso."

