permissions:
  contents: write

jobs:
  extract-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and extract ZIP
        run: |
          ZIP_FILE="$(find . -maxdepth 1 -type f -iname '*.zip' -print -quit || true)"
          if [ -z "$ZIP_FILE" ]; then
            echo "Nenhum .zip encontrado na raiz do repositório."
            exit 1
          fi
          echo "Extraindo $ZIP_FILE"
          sudo apt-get update -y && sudo apt-get install -y unzip
          unzip -q "$ZIP_FILE" -d extracted
          rm -f "$ZIP_FILE"
          shopt -s dotglob
          cp -a extracted/* .
          rm -rf extracted

      - name: Set up Git credentials (using PAT)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "Yohan Linero"
          git config --global user.email "yuricv89@hotmail.com"
          git remote set-url origin https://NomasIA:${GH_PAT}@github.com/${{ github.repository }}.git

      - name: Commit and push extracted files
        run: |
          git add -A
          git commit -m "Extraído automaticamente pelo GitHub Actions" || echo "Sem alterações"
          git push origin HEAD:${{ github.ref_name }}
