name: Extract project
permissions:
  contents: write

on:
  workflow_dispatch: {}
  push:
    paths:
      - "**/*.zip"

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Find and extract ZIP
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip
          ZIP_FILE="$(ls -1 *.zip 2>/dev/null | head -n 1 || true)"
          if [ -z "$ZIP_FILE" ]; then
            echo "Nenhum .zip encontrado na raiz do repositório."
            exit 1
          fi
          echo "Extraindo: $ZIP_FILE"
          unzip -o "$ZIP_FILE" -d .
          rm -f "$ZIP_FILE"

      - name: Commit extracted files
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "Yohan Linero"
          git config user.email "yuricv89@hotmail.com"
          git remote set-url origin https://NomasIA:${GH_PAT}@github.com/NomasIA/Aguia-finance.git
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Extraído automaticamente pelo GitHub Actions"
            git push origin main
          else
            echo "Sem mudanças para commitar."
          fi

       
